name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build papercut
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          context: .
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/papercut:latest