name: ci

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build papercut for ubuntu
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.ubuntu
          context: .
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/papercut:latest-ubuntu
      - name: Build papercut for alpine
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.alpine
          context: .
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/papercut:latest-alpine