name: tag

on:
  push:
    tags:
      - 'papercut-*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: get current tag
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/papercut-}
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build papercut
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          context: .
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/papercut:${{ steps.get_tag.outputs.TAG }}
          push: true
